spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
            redirect-uri: "app-google-redirect-url"
          github:
            client-id: github-client-id
            client-secret: github-client-secret
            redirect-uri: "app-github-redirect-url" 
